modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All rights reserved"

[[mods]]
modId = "playerplates"
version = "${version}"
displayName = "Player Plates"
authors = "Gaz"
description = '''
Adds a few extra pressure plates types that can be used to detect players, mobs, and items.
'''
credits = "ktraw2"
#logoFile = ""

[[dependencies.playerplates]]
modId = "neoforge"
required = true
versionRange = "[26.1,26.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.playerplates]]
modId = "minecraft"
required = true
versionRange = "[26.1,26.2)"
ordering = "NONE"
side = "BOTH"
